# Generated by Django 5.1.6 on 2025-03-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_categ_slug_alter_products_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name', 'slug'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
